import = ["~/.config/alacritty/dracula.toml"]

[font]
size = 14.0

[font.bold]
family = "FiraCode"
style = "Bold"

[font.bold_italic]
family = "FiraCode"
style = "Bold Italic"

[font.italic]
family = "FiraCode"
style = "Italic"

[font.normal]
family = "FiraCode"
style = "Regular"
