theme = "gruvbox"

[editor]
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.insert]
j = { k = "normal_mode" }

[editor.soft-wrap]
enable = true
wrap-indicator = "↩ "

[editor.statusline]
right = ["position", "position-percentage", "total-line-numbers"]

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
